apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: s9l113g2o-python
  janus-idp.io/tekton: s9l113g2o-python
  backstage.io/kubernetes-id: s9l113g2o-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: s9l113g2o-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
